name: example
description: Charts-Flutter Demo
environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.16.0
  intl: ^0.20.2
flutter:
  uses-material-design: true
